config/routes.rb
Rails.application.routes.draw do

  root 'tracks#index'

  resources :tracks

end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello world!"
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new   
  end

  def edit
    @track = Track.find(params[:id])
  end
  
  def create
    @track = Track.new(track_params)
    @track.save
    redirect_to @track
  end

  def update
    @track = Track.find(params[:id])
    
    if @track.update(track_params)
      redirect_to @track
    else
      render 'edit'
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to tracks_path
  end

  #It could be possible for track hash to contain values beyond which you want to save to your model!
  private
  def track_params
    params.require(:track).permit(:name, :artist, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/edit.html.erb
<h1> Edit Track </h1>
<%= form_for :track, url: track_path(@track), method: :patch do |f| %>

   <% if @track.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@track.errors.count, "error") %> prohibited
         this track from being saved:
       </h2>
       <ul>
         <% @track.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
        </ul>
      </div>
    <% end %>
               
    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>
           
    <p>
    <%= f.label :artist %><br>
    <%= f.text_area :artist %>
    </p>

    <p>
    <%= f.label :url %><br>
    <%= f.text_area :url %>
    </p>

    <p>
    <%= f.submit %>
    </p>
                           
<% end %>
                       
    <%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1> ALL TRACKS </h1>

      <table class="table">
        <tr>
          <th>Name</th>
          <th>Artist</th>
          <th>URL</th>
          <th colspan="3"></th>
        </tr>
        <% @tracks.each do |track| %>
          <tr>
            <td><%= track.name %></td>
            <td><%= track.artist %></td>
            <td><a target="_blank" href=<%= track.url %>><%= track.url.length > 30 ? track.url[0..30] + "..." : track.url%></a></td>
            <td><%= link_to 'show', track_path(track) %></td>
            <td><%= link_to 'edit', edit_track_path(track) %></td>
            <td><%= link_to 'delete', track_path(track), method: :delete, data: {confirm: 'Are you sure?'} %></td> 
          </tr>
        <% end %>
      <tr>
        <%= form_for :track, url: tracks_path, :html => {:class => "form-inline"} do |f| %>
          <td>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "name" %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= f.text_field :artist, class: "form-control", placeholder: "artist" %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= f.text_field :url, class: "form-control", placeholder: "URL" %>
          </div>
        </td>
        <td colspan="3">
          <%= f.submit "Add Track", class: "btn btn-block btn-default"%>
        </td>
        <% end %>
      </tr>
      </table>
      
      </div>
    </div>
  </div>
</div>

app/views/tracks/new.html.erb
<h1>NEW TRACKS PAGE </h1>

<%= form_for :track, url: tracks_path, :html => {:class => "form-inline"}  do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'back', tracks_path %>

app/views/tracks/show.html.erb
<h1>SHOWING TRACK</h1>

<p>
<strong>Name:</strong>
<%= @track.name %>
</p>

<p>
  <strong>Artist</strong>
  <%= @track.artist %>
</p>

<p>
  <strong>URL:</strong>
  <%= @track.url %>
</p>

<%= link_to 'back', tracks_path %>